apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.appName }}
rules:
  - apiGroups: ["tf-reconcile.lego.com"]
    resources: ["workspaces"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  - apiGroups: ["tf-reconcile.lego.com"]
    resources: ["workspaces/status"]
    verbs: ["get", "update", "patch"]
  
  - apiGroups: ["tf-reconcile.lego.com"]
    resources: ["plans"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: ["tf-reconcile.lego.com"]
    resources: ["plans/status"]
    verbs: ["get", "update", "patch"]
    
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]

  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
    
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]

  - apiGroups: [""]                 # core API group
    resources: ["serviceaccounts"]  # what the reflector is listing
    verbs: ["get", "list", "watch"] # or add create/update/patch if you need them
