apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/version: {{ .Values.image.tag }}
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/component: terraform-reconciler
    app.kubernetes.io/part-of: terraform-reconciler
  name: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/version: {{ .Values.image.tag }}
        app.kubernetes.io/name: {{ .Values.appName }}
        app.kubernetes.io/component: terraform-reconciler
        app.kubernetes.io/part-of: terraform-reconciler
        app: {{ .Values.appName }}
    spec:
      serviceAccountName: {{ .Values.appName }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: terraform-data
          emptyDir: {}
      containers:
      - name: {{ .Values.appName }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        volumeMounts:
          - mountPath: /tmp
            name: terraform-data
        env:
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
