apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "operator.fullname" . }}-configmap
data:
  RT_NAMESPACE_LABEL: {{ .Values.namespaceLabel | quote }}
  RT_LOG_LEVEL: {{ .Values.logLevel | quote }}
  RT_NAMESPACE: {{ .Release.Namespace | quote }}
  {{ range $key, $value := .Values.defaultServiceAccountConfig }}
  {{- upper (printf "rt_default_sa_config__%s" $key) }}: {{ $value | quote }}
  {{ end }}
