{{ if .Values.podMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    {{- include "operator.labels" . | nindent 4 }}
    {{- with .Values.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: runtime-id-operator
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "operator.selectorLabels" . | nindent 8 }}
  podMetricsEndpoints:
    - port: http-metrics
      interval: 30s
      path: /metrics
{{- end }}