apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "operator.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "operator.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "operator.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator.fullname" . }}
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["list", "get", "watch", "patch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list", "get", "watch"]
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "list", "watch"]
