---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - tf-reconcile.lukaspj.io
  resources:
  - providers
  - tfmodules
  - workspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tf-reconcile.lukaspj.io
  resources:
  - providers/finalizers
  - tfmodules/finalizers
  - workspaces/finalizers
  verbs:
  - update
- apiGroups:
  - tf-reconcile.lukaspj.io
  resources:
  - providers/status
  - tfmodules/status
  - workspaces/status
  verbs:
  - get
  - patch
  - update
