name: Build and Push Image to GHCR

on:
  pull_request:
    paths:
      - "**/*.go"
      - go.mod
      - .github/workflows/build-push.yml
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  actions: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Generate build date
        id: date
        run: echo "BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_OUTPUT

      - name: Docker meta 📦
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        with:
          images: |
            ghcr.io/${{ github.repository }}/kube-tf-reconciler
          tags: |
            type=semver,pattern={{version}}
            type=sha
            type=ref,event=pr
          flavor: |
            latest=false
  
      - name: Setup Docker Buildx 🛠️
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
#      - name: Get Access Token
#        uses: ./.github/actions/artifactory-access-token
#        id: access-token
#        with:
#          provider: kube-tf-reconciler
#          repository: ${{ github.event.repository.name }}
#
      - uses: jfrog/setup-jfrog-cli@deda456d982fc5e9a7a020b63eb0d2968aedd33e # v5.1.0
        id: jfrog-cli
        env:
          JF_URL: artifactory.novus.legogroup.io
        with:
          oidc-provider-name: kube-tf-reconciler
          oidc-audience: lego-github

      - name: Login to JFrog 🐸
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: artifactory.novus.legogroup.io
          username: ${{ steps.jfrog-cli.outputs.oidc-user }}
          password: ${{ steps.jfrog-cli.outputs.oidc-token }}
      - name: Login to GHCR 🔑
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push 🚀
        id: build
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          build-args: |
            SHA=${{ github.sha }}
            DATE=${{ steps.date.outputs.BUILD_DATE }}
