name: 'Dependency Review'
on:
  pull_request:
  push:
    branches:
      - main

# The API requires write permission on the repository to submit dependencies
permissions:
  contents: write
  pull-requests: write

jobs:
  go-action-detection:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run snapshot action
        uses: actions/go-dependency-submission@v2
        with:
            # Required: Define the repo path to the go.mod file used by the
            # build target
            go-mod-path: go.mod
            
            #
            # Optional: Define the path of a build target (a file with a
            # `main()` function) If not defined, this Action will collect all
            # dependencies used by all build targets for the module, which may
            # include Go dependencies used by tests and tooling.
            go-build-target: main.go

  dependency-review:
    runs-on: ubuntu-latest
    needs: go-action-detection
    if: github.event_name == 'pull_request'
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: always
          fail-on-severity: moderate
          allow-dependencies-licenses: "pkg:golang/github.com/hashicorp/terraform-json"
          allow-licenses:
            BSD-2-Clause-Patent,
            ADSL,
            Apache-2.0,
            APAFML,
            BSD-1-Clause,
            BSD-2-Clause,
            BSD-2-Clause-FreeBSD,
            BSD-2-Clause-NetBSD,
            BSL-1.0,
            DSDP,
            ECL-1.0,
            ECL-2.0,
            ImageMagick,
            ISC,
            Linux-OpenIB,
            MIT,
            MS-PL,
            Mup,
            PostgreSQL,
            Spencer-99,
            UPL-1.0,
            Xerox,
            0BSD,
            AFL-1.1,
            AFL-1.2,
            AFL-2.0,
            AFL-2.1,
            AFL-3.0,
            AMDPLPA,
            AML,
            AMPAS,
            ANTLR-PD,
            Apache-1.0,
            Apache-1.1,
            Artistic-2.0,
            Bahyph,
            Barr,
            BSD-3-Clause,
            BSD-3-Clause-Attribution,
            BSD-3-Clause-Clear,
            BSD-3-Clause-LBNL,
            BSD-3-Clause-No-Nuclear-License-2014,
            BSD-3-Clause-No-Nuclear-Warranty,
            BSD-4-Clause,
            BSD-4-Clause-UC,
            BSD-Source-Code,
            bzip2-1.0.5,
            bzip2-1.0.6,
            CC0-1.0,
            CNRI-Jython,
            CNRI-Python,
            CNRI-Python-GPL-Compatible,
            Cube,
            curl,
            eGenix,
            Entessa,
            FTL,
            IBM-pibs,
            ICU,
            Info-ZIP,
            Intel,
            JasPer-2.0,
            Libpng,
            libtiff,
            LPPL-1.3c,
            MIT-0,
            MIT-advertising,
            MIT-CMU,
            MIT-enna,
            MIT-feh,
            MITNFA,
            MTLL,
            Multics,
            Naumen,
            NCSA,
            Net-SNMP,
            NetCDF,
            NTP,
            OLDAP-2.0,
            OLDAP-2.0.1,
            OLDAP-2.1,
            OLDAP-2.2,
            OLDAP-2.2.1,
            OLDAP-2.2.2,
            OLDAP-2.3,
            OLDAP-2.2.1,
            OLDAP-2.2.2,
            OLDAP-2.3,
            OLDAP-2.4,
            OLDAP-2.5,
            OLDAP-2.6,
            OLDAP-2.7,
            OLDAP-2.8,
            OML,
            OpenSSL,
            PHP-3.0,
            PHP-3.01,
            Plexus,
            Python-2.0,
            Ruby,
            Saxpath,
            SGI-B-2.0,
            SMLNJ,
            SWL,
            TCL,
            TCP-wrappers,
            Unicode-3.0,
            Unicode-DFS-2015,
            Unicode-DFS-2016,
            Unlicense
